### ISSUE TITLE
БОТ ХУЙНЯ

### ISSUE THREAD

**Issue by StrahovDev** [AkainuBot/AkainuWeb#6]
УДАЛИ СЕБЯ И БОТА

**Comment by SayHelloRoman** [comment]
We will definitely do this in future updates.

**Comment by StrahovDev** [comment]
Жду обнову

**Comment by AkylKa** [comment]
Казнь хорошим людям)))

**Comment by RedLeader167** [comment]
Жду обнову, а ещё как глисты лечить
